version: 1.0.{build}
image: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\MIG.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - MIG.Tests/bin/Debug/MIG.Tests.dll
after_test:
  - ps: .\MIG\nuget_pack.ps1
artifacts:
  - path: .\MIG\bin\Debug\MIG.dll
    name: MIG
    type: File
  - path: '*.nupkg'
    name: MIG nupkg
    type: NuGetPackage
deploy:
  - provider: GitHub
    auth_token:
      secure: 1aMBEFi1qBAoV4H+LYx7hoVLgXJfndGoQ8I8qjLsoxXNA1zS+zgQHi2zVlRrmw1v
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: 7O2WL0TVC1giRSfy22cZS5JZfQzVRinF8TA73QIMKmIxWaGxNUNIm/Kp8acL+CK2
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

